a = input("Insira a 1 nota ")
aInt = int(a)
b = input("Insira a 2 nota ")
bInt = int(b)
c = input ("Insira a 3 nota ")
cInt = int(c)
d = input("Insira a 4 nota ")
dInt = int(d)
Soma = (aInt + bInt + cInt + dInt)
print(Soma/4)